In [ ]:
def func2():
    return 5, 4

In [1]:
type(func2())

NameError: name 'func2' is not defined

In [2]:
def func2():
    return 5,4

In [3]:
type(func2())

tuple

In [4]:
def func3():
    return [5,4]

In [5]:
type(func3())

list

In [6]:
func2()

(5, 4)

In [7]:
func3()

[5, 4]

In [12]:
def func4():
    return list [5, 4]

In [13]:
x = np.arange(5)
print(x)

NameError: name 'np' is not defined

In [14]:
import numpy as np
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [15]:
:3


SyntaxError: invalid syntax (<ipython-input-15-e78c69b6067f>, line 1)

In [16]:
np.shape(x)

(5,)

In [17]:
type((5,))

tuple

In [18]:
type(5)

int

In [19]:
print("hello")

hello


In [20]:
x = [1, 2, 3]

In [22]:
np.concatenate(x)

ValueError: zero-dimensional arrays cannot be concatenated

In [23]:
[1] + x

[1, 1, 2, 3]

In [24]:
np.array(x)

array([1, 2, 3])

In [26]:
np.concatenate(np.array(x))

ValueError: zero-dimensional arrays cannot be concatenated

In [27]:
1 + np.array(x)

array([2, 3, 4])

In [35]:
#what happened to the extra [1]?

In [29]:
zeros = np.zeros((5,5), dtype=float)

In [30]:
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [34]:
#this is a matrix :o

In [32]:
np.shape(zeros)

(5, 5)

In [33]:
#np.shape tells you the "shape" of your data set

In [36]:
zeros[0]

array([0., 0., 0., 0., 0.])

In [37]:
#

In [38]:
#

In [39]:
x

[1, 2, 3]

In [40]:
#to slice the list

In [41]:
x[2:3]

[3]

In [42]:
#"from the index position 2 and up but not include index 3"